### ISSUE TITLE
Support object progress

### ISSUE THREAD

**Issue by melalj** [s-r-x/bull-monitor#14]
I keep getting a rendering error when the job progress is an object `{ "percents:" 100, "currentStep": "finished" }`:

```
Error: Int cannot represent non-integer value: { percents: 100, currentStep: "finished" }: {"response":{"errors":[{"message":"Int cannot represent non-integer value: { percents: 100, currentStep: \"finished\" }","locations":[{"line":5,"column":5}],"path":["jobs",0,"progress"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"message":"Int cannot represent non-integer value: { percents: 100, currentStep: \"finished\" }"}...
```

Maybe it should be a way to with discard the progress, or be able to have an option to map the int value with the right key

**Comment by s-r-x** [comment]
are you using bullmq? i'm asking because bull always returns progress as a number(if the docs are correct). this api/ui is made specifically for bull

**Comment by fritx** [comment]
+1 same error here. bullmq supports object progress @s-r-x 

![image](https://user-images.githubusercontent.com/6647633/155887151-0abe6ab0-3b3d-457c-a086-e4623ca4de4c.png)

![image](https://user-images.githubusercontent.com/6647633/155887109-80ea45c7-bfe5-4007-ab6f-028dd11e4a77.png)

**Comment by fritx** [comment]
awesome work btw! I'm also willing to provide PR as well

**Comment by s-r-x** [comment]
@fritx hmm, i have no idea why graphql throws an error on this one, because bull-monitor api always [converts](https://github.com/s-r-x/bull-monitor/blob/main/packages/root/src/bullmq-adapter.ts#L40) job progress to 0, if one is not a number. 
btw since we support bullmq now, non standard object progress should be pretty easy to implement: we just need to change its gql type to string and implement serialization.

**Comment by s-r-x** [comment]
@fritx LGTM

**Comment by s-r-x** [comment]
added in 3.5.0

**Comment by s-r-x** [comment]
@fritx bullmq support for the cli was added in 4.1.0 (there is a new "bullmq" flag)
