### ISSUE TITLE
Export entire queue as JSON

### ISSUE THREAD

**Issue by saade** [s-r-x/bull-monitor#26]
It would be nice to export the entire queue as a JSON file. Currently is only possible export selected items.

In this real life example, i need to export all 1k items to a file for further investigation
![image](https://user-images.githubusercontent.com/14329460/133471187-e146faf8-6e0e-48af-95e2-aed1d5e936fe.png)

**Comment by s-r-x** [comment]
@saade it seems like in your case you don't need export for the whole queue, but just a slice of jobs with "failed" status. in 2.4.0 i've added export for jobs, that matches the active query(status, search, whatever). looks like it should cover your needs. btw for export large amount of jobs i recommend you to use the graphql playground over the bull-monitor ui, in order to return only the fields, that you are interested in. just specify 0 offset, some large limit, and you're good to go.
