### ISSUE TITLE
support querying prioritized JobStatus

### ISSUE THREAD

**Issue by lilei1988** [s-r-x/bull-monitor#71]
Hi @s-r-x，
The priority job cannot be found in the UI, could you support querying the prioritized status, thanks

**Comment by s-r-x** [comment]
@lilei1988 actually you can query jobs by priority using the search input ([reference](https://github.com/s-r-x/bull-monitor/blob/main/search-examples.md))

something like this maybe?
```
opts.priority >= 1
```

**Comment by arielvieira** [comment]
@s-r-x Since the BullMQ >4.0, Prioritized Jobs have their own status and are no longer bundled in `waiting`.

You can learn more here in the [PR](https://github.com/taskforcesh/bullmq/pull/1984) and in the [blog post here](https://bullmq.io/news/062123/faster-priority-jobs/). 

So in order to tackle this, bull-monitor would need to support a new status called `prioritized`. Here is the new methods from BullMQ 4.

```ts
    /**
     * Returns the number of jobs in prioritized status.
     */
    getPrioritizedCount(): Promise<number>;
    
    
    /**
     * Returns the jobs that are in the "prioritized" status.
     * @param start - zero based index from where to start returning jobs.
     * @param end - zero based index where to stop returning jobs.
     */
    getPrioritized(start?: number, end?: number): Promise<Job<DataType, ResultType, NameType>[]>;
```

**Comment by s-r-x** [comment]
@arielvieira i see... thx for the info. i'll try to look into it.

**Comment by s-r-x** [comment]
added in 5.2.0
